@echo off
echo Fixing Prisma engines...
echo.
echo Removing corrupted engine files...
rmdir /s /q node_modules\@prisma\engines 2>nul
rmdir /s /q node_modules\.prisma 2>nul
echo.
echo Reinstalling Prisma packages...
call npm install prisma @prisma/client --force
echo.
echo Generating Prisma client...
call npx prisma generate
echo.
echo Starting Prisma Studio...
call npx prisma studio
