const { PrismaClient } = require('@prisma/client');
const bcrypt = require('bcryptjs');

const prisma = new PrismaClient();

async function main() {
  console.log('🌱 Starting Pakistan Hotels database seed...');
  console.log('🇵🇰 Cities: Okara, Lahore, Sheikhupura, Multan');

  const rooms = [
  {
    "roomNumber": "OK-001",
    "type": "Budget Room",
    "title": "Budget Room - Okara",
    "description": "Experience authentic Pakistani hospitality in our budget room located in Okara. Perfect for solo travelers or couples.",
    "location": "Okara, Punjab",
    "capacity": 2,
    "pricePerNight": 4566,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"TV\",\"Attached Bathroom\",\"Room Service\"]",
    "size": "15-20 sqm",
    "bedType": "Double Bed",
    "isAvailable": true,
    "featured": false
  },
  {
    "roomNumber": "OK-002",
    "type": "Budget Room",
    "title": "Budget Room - Okara",
    "description": "Experience authentic Pakistani hospitality in our budget room located in Okara. Perfect for solo travelers or couples.",
    "location": "Okara, Punjab",
    "capacity": 2,
    "pricePerNight": 3262,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"TV\",\"Attached Bathroom\",\"Room Service\"]",
    "size": "15-20 sqm",
    "bedType": "Double Bed",
    "isAvailable": true,
    "featured": false
  },
  {
    "roomNumber": "OK-003",
    "type": "Budget Room",
    "title": "Budget Room - Okara",
    "description": "Experience authentic Pakistani hospitality in our budget room located in Okara. Perfect for solo travelers or couples.",
    "location": "Okara, Punjab",
    "capacity": 2,
    "pricePerNight": 3034,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"TV\",\"Attached Bathroom\",\"Room Service\"]",
    "size": "15-20 sqm",
    "bedType": "Double Bed",
    "isAvailable": true,
    "featured": false
  },
  {
    "roomNumber": "OK-004",
    "type": "Economy Room",
    "title": "Economy Room - Okara",
    "description": "Experience authentic Pakistani hospitality in our economy room located in Okara. Perfect for small families.",
    "location": "Okara, Punjab",
    "capacity": 3,
    "pricePerNight": 7790,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"LED TV\",\"Work Desk\",\"Mini Fridge\",\"Tea/Coffee Maker\"]",
    "size": "20-25 sqm",
    "bedType": "Queen Bed",
    "isAvailable": true,
    "featured": false
  },
  {
    "roomNumber": "OK-005",
    "type": "Economy Room",
    "title": "Economy Room - Okara",
    "description": "Experience authentic Pakistani hospitality in our economy room located in Okara. Perfect for small families.",
    "location": "Okara, Punjab",
    "capacity": 3,
    "pricePerNight": 9978,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"LED TV\",\"Work Desk\",\"Mini Fridge\",\"Tea/Coffee Maker\"]",
    "size": "20-25 sqm",
    "bedType": "Queen Bed",
    "isAvailable": true,
    "featured": false
  },
  {
    "roomNumber": "OK-006",
    "type": "Economy Room",
    "title": "Economy Room - Okara",
    "description": "Experience authentic Pakistani hospitality in our economy room located in Okara. Perfect for small families.",
    "location": "Okara, Punjab",
    "capacity": 3,
    "pricePerNight": 9511,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"LED TV\",\"Work Desk\",\"Mini Fridge\",\"Tea/Coffee Maker\"]",
    "size": "20-25 sqm",
    "bedType": "Queen Bed",
    "isAvailable": true,
    "featured": false
  },
  {
    "roomNumber": "OK-007",
    "type": "Standard Room",
    "title": "Standard Room - Okara",
    "description": "Experience authentic Pakistani hospitality in our standard room located in Okara. Perfect for solo travelers or couples.",
    "location": "Okara, Punjab",
    "capacity": 2,
    "pricePerNight": 14216,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"Smart TV\",\"Work Desk\",\"Mini Fridge\",\"Safe\",\"Premium Bedding\"]",
    "size": "25-30 sqm",
    "bedType": "King Bed",
    "isAvailable": true,
    "featured": false
  },
  {
    "roomNumber": "OK-008",
    "type": "Standard Room",
    "title": "Standard Room - Okara",
    "description": "Experience authentic Pakistani hospitality in our standard room located in Okara. Perfect for solo travelers or couples.",
    "location": "Okara, Punjab",
    "capacity": 2,
    "pricePerNight": 11614,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"Smart TV\",\"Work Desk\",\"Mini Fridge\",\"Safe\",\"Premium Bedding\"]",
    "size": "25-30 sqm",
    "bedType": "King Bed",
    "isAvailable": true,
    "featured": false
  },
  {
    "roomNumber": "OK-009",
    "type": "Standard Room",
    "title": "Standard Room - Okara",
    "description": "Experience authentic Pakistani hospitality in our standard room located in Okara. Perfect for solo travelers or couples.",
    "location": "Okara, Punjab",
    "capacity": 2,
    "pricePerNight": 10218,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"Smart TV\",\"Work Desk\",\"Mini Fridge\",\"Safe\",\"Premium Bedding\"]",
    "size": "25-30 sqm",
    "bedType": "King Bed",
    "isAvailable": true,
    "featured": false
  },
  {
    "roomNumber": "OK-010",
    "type": "Standard Room",
    "title": "Standard Room - Okara",
    "description": "Experience authentic Pakistani hospitality in our standard room located in Okara. Perfect for solo travelers or couples.",
    "location": "Okara, Punjab",
    "capacity": 2,
    "pricePerNight": 10530,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"Smart TV\",\"Work Desk\",\"Mini Fridge\",\"Safe\",\"Premium Bedding\"]",
    "size": "25-30 sqm",
    "bedType": "King Bed",
    "isAvailable": true,
    "featured": false
  },
  {
    "roomNumber": "OK-011",
    "type": "Deluxe Room",
    "title": "Deluxe Room - Okara",
    "description": "Experience authentic Pakistani hospitality in our deluxe room located in Okara. Perfect for small families.",
    "location": "Okara, Punjab",
    "capacity": 4,
    "pricePerNight": 23550,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"Smart TV\",\"Mini Bar\",\"Seating Area\",\"Premium Bedding\",\"Bathrobe\",\"City View\"]",
    "size": "30-40 sqm",
    "bedType": "King Bed + Sofa Bed",
    "isAvailable": true,
    "featured": false
  },
  {
    "roomNumber": "OK-012",
    "type": "Deluxe Room",
    "title": "Deluxe Room - Okara",
    "description": "Experience authentic Pakistani hospitality in our deluxe room located in Okara. Perfect for small families.",
    "location": "Okara, Punjab",
    "capacity": 4,
    "pricePerNight": 24765,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"Smart TV\",\"Mini Bar\",\"Seating Area\",\"Premium Bedding\",\"Bathrobe\",\"City View\"]",
    "size": "30-40 sqm",
    "bedType": "King Bed + Sofa Bed",
    "isAvailable": true,
    "featured": false
  },
  {
    "roomNumber": "OK-013",
    "type": "Deluxe Room",
    "title": "Deluxe Room - Okara",
    "description": "Experience authentic Pakistani hospitality in our deluxe room located in Okara. Perfect for small families.",
    "location": "Okara, Punjab",
    "capacity": 4,
    "pricePerNight": 23634,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"Smart TV\",\"Mini Bar\",\"Seating Area\",\"Premium Bedding\",\"Bathrobe\",\"City View\"]",
    "size": "30-40 sqm",
    "bedType": "King Bed + Sofa Bed",
    "isAvailable": true,
    "featured": false
  },
  {
    "roomNumber": "OK-014",
    "type": "Deluxe Room",
    "title": "Deluxe Room - Okara",
    "description": "Experience authentic Pakistani hospitality in our deluxe room located in Okara. Perfect for small families.",
    "location": "Okara, Punjab",
    "capacity": 4,
    "pricePerNight": 18051,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"Smart TV\",\"Mini Bar\",\"Seating Area\",\"Premium Bedding\",\"Bathrobe\",\"City View\"]",
    "size": "30-40 sqm",
    "bedType": "King Bed + Sofa Bed",
    "isAvailable": true,
    "featured": false
  },
  {
    "roomNumber": "OK-015",
    "type": "Business Room",
    "title": "Business Room - Okara",
    "description": "Experience authentic Pakistani hospitality in our business room located in Okara. Perfect for solo travelers or couples.",
    "location": "Okara, Punjab",
    "capacity": 2,
    "pricePerNight": 21389,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"Smart TV\",\"Executive Desk\",\"Printer Access\",\"Business Center\",\"Meeting Room Access\"]",
    "size": "28-35 sqm",
    "bedType": "King Bed",
    "isAvailable": true,
    "featured": false
  },
  {
    "roomNumber": "OK-016",
    "type": "Business Room",
    "title": "Business Room - Okara",
    "description": "Experience authentic Pakistani hospitality in our business room located in Okara. Perfect for solo travelers or couples.",
    "location": "Okara, Punjab",
    "capacity": 2,
    "pricePerNight": 26150,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"Smart TV\",\"Executive Desk\",\"Printer Access\",\"Business Center\",\"Meeting Room Access\"]",
    "size": "28-35 sqm",
    "bedType": "King Bed",
    "isAvailable": true,
    "featured": false
  },
  {
    "roomNumber": "OK-017",
    "type": "Business Room",
    "title": "Business Room - Okara",
    "description": "Experience authentic Pakistani hospitality in our business room located in Okara. Perfect for solo travelers or couples.",
    "location": "Okara, Punjab",
    "capacity": 2,
    "pricePerNight": 21119,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"Smart TV\",\"Executive Desk\",\"Printer Access\",\"Business Center\",\"Meeting Room Access\"]",
    "size": "28-35 sqm",
    "bedType": "King Bed",
    "isAvailable": true,
    "featured": false
  },
  {
    "roomNumber": "OK-018",
    "type": "Junior Suite",
    "title": "Junior Suite - Okara",
    "description": "Experience authentic Pakistani hospitality in our junior suite located in Okara. Perfect for small families.",
    "location": "Okara, Punjab",
    "capacity": 3,
    "pricePerNight": 32964,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"Smart TV\",\"Living Area\",\"Mini Bar\",\"Premium Coffee\",\"Work Station\",\"City View\"]",
    "size": "35-45 sqm",
    "bedType": "King Bed",
    "isAvailable": true,
    "featured": false
  },
  {
    "roomNumber": "OK-019",
    "type": "Junior Suite",
    "title": "Junior Suite - Okara",
    "description": "Experience authentic Pakistani hospitality in our junior suite located in Okara. Perfect for small families.",
    "location": "Okara, Punjab",
    "capacity": 3,
    "pricePerNight": 30865,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"Smart TV\",\"Living Area\",\"Mini Bar\",\"Premium Coffee\",\"Work Station\",\"City View\"]",
    "size": "35-45 sqm",
    "bedType": "King Bed",
    "isAvailable": true,
    "featured": false
  },
  {
    "roomNumber": "OK-020",
    "type": "Junior Suite",
    "title": "Junior Suite - Okara",
    "description": "Experience authentic Pakistani hospitality in our junior suite located in Okara. Perfect for small families.",
    "location": "Okara, Punjab",
    "capacity": 3,
    "pricePerNight": 30129,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"Smart TV\",\"Living Area\",\"Mini Bar\",\"Premium Coffee\",\"Work Station\",\"City View\"]",
    "size": "35-45 sqm",
    "bedType": "King Bed",
    "isAvailable": true,
    "featured": false
  },
  {
    "roomNumber": "OK-021",
    "type": "Executive Suite",
    "title": "Executive Suite - Okara",
    "description": "Experience authentic Pakistani hospitality in our executive suite located in Okara. Perfect for large families or groups.",
    "location": "Okara, Punjab",
    "capacity": 6,
    "pricePerNight": 49796,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"55\\\" Smart TV\",\"Separate Living Room\",\"Mini Bar\",\"Premium Bedding\",\"Executive Lounge\",\"Butler Service\"]",
    "size": "50-65 sqm",
    "bedType": "King Bed + Sofa Bed",
    "isAvailable": true,
    "featured": true
  },
  {
    "roomNumber": "OK-022",
    "type": "Executive Suite",
    "title": "Executive Suite - Okara",
    "description": "Experience authentic Pakistani hospitality in our executive suite located in Okara. Perfect for large families or groups.",
    "location": "Okara, Punjab",
    "capacity": 6,
    "pricePerNight": 37742,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"55\\\" Smart TV\",\"Separate Living Room\",\"Mini Bar\",\"Premium Bedding\",\"Executive Lounge\",\"Butler Service\"]",
    "size": "50-65 sqm",
    "bedType": "King Bed + Sofa Bed",
    "isAvailable": true,
    "featured": true
  },
  {
    "roomNumber": "OK-023",
    "type": "Executive Suite",
    "title": "Executive Suite - Okara",
    "description": "Experience authentic Pakistani hospitality in our executive suite located in Okara. Perfect for large families or groups.",
    "location": "Okara, Punjab",
    "capacity": 6,
    "pricePerNight": 39787,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"55\\\" Smart TV\",\"Separate Living Room\",\"Mini Bar\",\"Premium Bedding\",\"Executive Lounge\",\"Butler Service\"]",
    "size": "50-65 sqm",
    "bedType": "King Bed + Sofa Bed",
    "isAvailable": true,
    "featured": true
  },
  {
    "roomNumber": "OK-024",
    "type": "Family Suite",
    "title": "Family Suite - Okara",
    "description": "Experience authentic Pakistani hospitality in our family suite located in Okara. Perfect for large families or groups.",
    "location": "Okara, Punjab",
    "capacity": 6,
    "pricePerNight": 40066,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"Smart TV\",\"Kitchenette\",\"Separate Bedrooms\",\"Family Games\",\"Kids Welcome Pack\",\"Dining Area\"]",
    "size": "55-70 sqm",
    "bedType": "King + Twin Beds",
    "isAvailable": true,
    "featured": false
  },
  {
    "roomNumber": "OK-025",
    "type": "Family Suite",
    "title": "Family Suite - Okara",
    "description": "Experience authentic Pakistani hospitality in our family suite located in Okara. Perfect for large families or groups.",
    "location": "Okara, Punjab",
    "capacity": 6,
    "pricePerNight": 41605,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"Smart TV\",\"Kitchenette\",\"Separate Bedrooms\",\"Family Games\",\"Kids Welcome Pack\",\"Dining Area\"]",
    "size": "55-70 sqm",
    "bedType": "King + Twin Beds",
    "isAvailable": true,
    "featured": false
  },
  {
    "roomNumber": "OK-026",
    "type": "Family Suite",
    "title": "Family Suite - Okara",
    "description": "Experience authentic Pakistani hospitality in our family suite located in Okara. Perfect for large families or groups.",
    "location": "Okara, Punjab",
    "capacity": 6,
    "pricePerNight": 32520,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"Smart TV\",\"Kitchenette\",\"Separate Bedrooms\",\"Family Games\",\"Kids Welcome Pack\",\"Dining Area\"]",
    "size": "55-70 sqm",
    "bedType": "King + Twin Beds",
    "isAvailable": true,
    "featured": false
  },
  {
    "roomNumber": "OK-027",
    "type": "Presidential Suite",
    "title": "Presidential Suite - Okara",
    "description": "Experience authentic Pakistani hospitality in our presidential suite located in Okara. Perfect for large families or groups.",
    "location": "Okara, Punjab",
    "capacity": 8,
    "pricePerNight": 52465,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"75\\\" Smart TV\",\"Full Kitchen\",\"Dining Area\",\"Premium Bedding\",\"Panoramic Views\",\"Concierge\",\"Butler Service\",\"Private Terrace\"]",
    "size": "80-120 sqm",
    "bedType": "King + Queen Beds",
    "isAvailable": true,
    "featured": true
  },
  {
    "roomNumber": "OK-028",
    "type": "Presidential Suite",
    "title": "Presidential Suite - Okara",
    "description": "Experience authentic Pakistani hospitality in our presidential suite located in Okara. Perfect for large families or groups.",
    "location": "Okara, Punjab",
    "capacity": 8,
    "pricePerNight": 78219,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"75\\\" Smart TV\",\"Full Kitchen\",\"Dining Area\",\"Premium Bedding\",\"Panoramic Views\",\"Concierge\",\"Butler Service\",\"Private Terrace\"]",
    "size": "80-120 sqm",
    "bedType": "King + Queen Beds",
    "isAvailable": true,
    "featured": true
  },
  {
    "roomNumber": "OK-029",
    "type": "Royal Suite",
    "title": "Royal Suite - Okara",
    "description": "Experience authentic Pakistani hospitality in our royal suite located in Okara. Perfect for large families or groups.",
    "location": "Okara, Punjab",
    "capacity": 10,
    "pricePerNight": 128442,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"85\\\" Smart TV\",\"Full Kitchen\",\"Multiple Bedrooms\",\"Dining Hall\",\"Premium Bedding\",\"Panoramic Views\",\"Personal Concierge\",\"24/7 Butler\",\"Private Terrace\",\"Jacuzzi\",\"Home Theater\"]",
    "size": "120-180 sqm",
    "bedType": "Multiple King Beds",
    "isAvailable": true,
    "featured": true
  },
  {
    "roomNumber": "LH-030",
    "type": "Budget Room",
    "title": "Budget Room - Lahore",
    "description": "Experience authentic Pakistani hospitality in our budget room located in Lahore. Perfect for solo travelers or couples.",
    "location": "Lahore, Punjab",
    "capacity": 2,
    "pricePerNight": 3552,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"TV\",\"Attached Bathroom\",\"Room Service\"]",
    "size": "15-20 sqm",
    "bedType": "Double Bed",
    "isAvailable": true,
    "featured": false
  },
  {
    "roomNumber": "LH-031",
    "type": "Budget Room",
    "title": "Budget Room - Lahore",
    "description": "Experience authentic Pakistani hospitality in our budget room located in Lahore. Perfect for solo travelers or couples.",
    "location": "Lahore, Punjab",
    "capacity": 2,
    "pricePerNight": 3437,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"TV\",\"Attached Bathroom\",\"Room Service\"]",
    "size": "15-20 sqm",
    "bedType": "Double Bed",
    "isAvailable": true,
    "featured": false
  },
  {
    "roomNumber": "LH-032",
    "type": "Budget Room",
    "title": "Budget Room - Lahore",
    "description": "Experience authentic Pakistani hospitality in our budget room located in Lahore. Perfect for solo travelers or couples.",
    "location": "Lahore, Punjab",
    "capacity": 2,
    "pricePerNight": 4525,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"TV\",\"Attached Bathroom\",\"Room Service\"]",
    "size": "15-20 sqm",
    "bedType": "Double Bed",
    "isAvailable": true,
    "featured": false
  },
  {
    "roomNumber": "LH-033",
    "type": "Economy Room",
    "title": "Economy Room - Lahore",
    "description": "Experience authentic Pakistani hospitality in our economy room located in Lahore. Perfect for small families.",
    "location": "Lahore, Punjab",
    "capacity": 3,
    "pricePerNight": 8070,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"LED TV\",\"Work Desk\",\"Mini Fridge\",\"Tea/Coffee Maker\"]",
    "size": "20-25 sqm",
    "bedType": "Queen Bed",
    "isAvailable": true,
    "featured": false
  },
  {
    "roomNumber": "LH-034",
    "type": "Economy Room",
    "title": "Economy Room - Lahore",
    "description": "Experience authentic Pakistani hospitality in our economy room located in Lahore. Perfect for small families.",
    "location": "Lahore, Punjab",
    "capacity": 3,
    "pricePerNight": 6856,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"LED TV\",\"Work Desk\",\"Mini Fridge\",\"Tea/Coffee Maker\"]",
    "size": "20-25 sqm",
    "bedType": "Queen Bed",
    "isAvailable": true,
    "featured": false
  },
  {
    "roomNumber": "LH-035",
    "type": "Economy Room",
    "title": "Economy Room - Lahore",
    "description": "Experience authentic Pakistani hospitality in our economy room located in Lahore. Perfect for small families.",
    "location": "Lahore, Punjab",
    "capacity": 3,
    "pricePerNight": 5914,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"LED TV\",\"Work Desk\",\"Mini Fridge\",\"Tea/Coffee Maker\"]",
    "size": "20-25 sqm",
    "bedType": "Queen Bed",
    "isAvailable": true,
    "featured": false
  },
  {
    "roomNumber": "LH-036",
    "type": "Standard Room",
    "title": "Standard Room - Lahore",
    "description": "Experience authentic Pakistani hospitality in our standard room located in Lahore. Perfect for solo travelers or couples.",
    "location": "Lahore, Punjab",
    "capacity": 2,
    "pricePerNight": 12343,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"Smart TV\",\"Work Desk\",\"Mini Fridge\",\"Safe\",\"Premium Bedding\"]",
    "size": "25-30 sqm",
    "bedType": "King Bed",
    "isAvailable": true,
    "featured": false
  },
  {
    "roomNumber": "LH-037",
    "type": "Standard Room",
    "title": "Standard Room - Lahore",
    "description": "Experience authentic Pakistani hospitality in our standard room located in Lahore. Perfect for solo travelers or couples.",
    "location": "Lahore, Punjab",
    "capacity": 2,
    "pricePerNight": 13836,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"Smart TV\",\"Work Desk\",\"Mini Fridge\",\"Safe\",\"Premium Bedding\"]",
    "size": "25-30 sqm",
    "bedType": "King Bed",
    "isAvailable": true,
    "featured": false
  },
  {
    "roomNumber": "LH-038",
    "type": "Standard Room",
    "title": "Standard Room - Lahore",
    "description": "Experience authentic Pakistani hospitality in our standard room located in Lahore. Perfect for solo travelers or couples.",
    "location": "Lahore, Punjab",
    "capacity": 2,
    "pricePerNight": 10886,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"Smart TV\",\"Work Desk\",\"Mini Fridge\",\"Safe\",\"Premium Bedding\"]",
    "size": "25-30 sqm",
    "bedType": "King Bed",
    "isAvailable": true,
    "featured": false
  },
  {
    "roomNumber": "LH-039",
    "type": "Standard Room",
    "title": "Standard Room - Lahore",
    "description": "Experience authentic Pakistani hospitality in our standard room located in Lahore. Perfect for solo travelers or couples.",
    "location": "Lahore, Punjab",
    "capacity": 2,
    "pricePerNight": 13550,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"Smart TV\",\"Work Desk\",\"Mini Fridge\",\"Safe\",\"Premium Bedding\"]",
    "size": "25-30 sqm",
    "bedType": "King Bed",
    "isAvailable": true,
    "featured": false
  },
  {
    "roomNumber": "LH-040",
    "type": "Deluxe Room",
    "title": "Deluxe Room - Lahore",
    "description": "Experience authentic Pakistani hospitality in our deluxe room located in Lahore. Perfect for small families.",
    "location": "Lahore, Punjab",
    "capacity": 4,
    "pricePerNight": 20925,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"Smart TV\",\"Mini Bar\",\"Seating Area\",\"Premium Bedding\",\"Bathrobe\",\"City View\"]",
    "size": "30-40 sqm",
    "bedType": "King Bed + Sofa Bed",
    "isAvailable": true,
    "featured": false
  },
  {
    "roomNumber": "LH-041",
    "type": "Deluxe Room",
    "title": "Deluxe Room - Lahore",
    "description": "Experience authentic Pakistani hospitality in our deluxe room located in Lahore. Perfect for small families.",
    "location": "Lahore, Punjab",
    "capacity": 4,
    "pricePerNight": 24636,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"Smart TV\",\"Mini Bar\",\"Seating Area\",\"Premium Bedding\",\"Bathrobe\",\"City View\"]",
    "size": "30-40 sqm",
    "bedType": "King Bed + Sofa Bed",
    "isAvailable": true,
    "featured": false
  },
  {
    "roomNumber": "LH-042",
    "type": "Deluxe Room",
    "title": "Deluxe Room - Lahore",
    "description": "Experience authentic Pakistani hospitality in our deluxe room located in Lahore. Perfect for small families.",
    "location": "Lahore, Punjab",
    "capacity": 4,
    "pricePerNight": 15005,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"Smart TV\",\"Mini Bar\",\"Seating Area\",\"Premium Bedding\",\"Bathrobe\",\"City View\"]",
    "size": "30-40 sqm",
    "bedType": "King Bed + Sofa Bed",
    "isAvailable": true,
    "featured": false
  },
  {
    "roomNumber": "LH-043",
    "type": "Deluxe Room",
    "title": "Deluxe Room - Lahore",
    "description": "Experience authentic Pakistani hospitality in our deluxe room located in Lahore. Perfect for small families.",
    "location": "Lahore, Punjab",
    "capacity": 4,
    "pricePerNight": 21980,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"Smart TV\",\"Mini Bar\",\"Seating Area\",\"Premium Bedding\",\"Bathrobe\",\"City View\"]",
    "size": "30-40 sqm",
    "bedType": "King Bed + Sofa Bed",
    "isAvailable": true,
    "featured": false
  },
  {
    "roomNumber": "LH-044",
    "type": "Business Room",
    "title": "Business Room - Lahore",
    "description": "Experience authentic Pakistani hospitality in our business room located in Lahore. Perfect for solo travelers or couples.",
    "location": "Lahore, Punjab",
    "capacity": 2,
    "pricePerNight": 20828,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"Smart TV\",\"Executive Desk\",\"Printer Access\",\"Business Center\",\"Meeting Room Access\"]",
    "size": "28-35 sqm",
    "bedType": "King Bed",
    "isAvailable": true,
    "featured": false
  },
  {
    "roomNumber": "LH-045",
    "type": "Business Room",
    "title": "Business Room - Lahore",
    "description": "Experience authentic Pakistani hospitality in our business room located in Lahore. Perfect for solo travelers or couples.",
    "location": "Lahore, Punjab",
    "capacity": 2,
    "pricePerNight": 24499,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"Smart TV\",\"Executive Desk\",\"Printer Access\",\"Business Center\",\"Meeting Room Access\"]",
    "size": "28-35 sqm",
    "bedType": "King Bed",
    "isAvailable": true,
    "featured": false
  },
  {
    "roomNumber": "LH-046",
    "type": "Business Room",
    "title": "Business Room - Lahore",
    "description": "Experience authentic Pakistani hospitality in our business room located in Lahore. Perfect for solo travelers or couples.",
    "location": "Lahore, Punjab",
    "capacity": 2,
    "pricePerNight": 25562,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"Smart TV\",\"Executive Desk\",\"Printer Access\",\"Business Center\",\"Meeting Room Access\"]",
    "size": "28-35 sqm",
    "bedType": "King Bed",
    "isAvailable": true,
    "featured": false
  },
  {
    "roomNumber": "LH-047",
    "type": "Junior Suite",
    "title": "Junior Suite - Lahore",
    "description": "Experience authentic Pakistani hospitality in our junior suite located in Lahore. Perfect for small families.",
    "location": "Lahore, Punjab",
    "capacity": 3,
    "pricePerNight": 29005,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"Smart TV\",\"Living Area\",\"Mini Bar\",\"Premium Coffee\",\"Work Station\",\"City View\"]",
    "size": "35-45 sqm",
    "bedType": "King Bed",
    "isAvailable": true,
    "featured": false
  },
  {
    "roomNumber": "LH-048",
    "type": "Junior Suite",
    "title": "Junior Suite - Lahore",
    "description": "Experience authentic Pakistani hospitality in our junior suite located in Lahore. Perfect for small families.",
    "location": "Lahore, Punjab",
    "capacity": 3,
    "pricePerNight": 26732,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"Smart TV\",\"Living Area\",\"Mini Bar\",\"Premium Coffee\",\"Work Station\",\"City View\"]",
    "size": "35-45 sqm",
    "bedType": "King Bed",
    "isAvailable": true,
    "featured": false
  },
  {
    "roomNumber": "LH-049",
    "type": "Junior Suite",
    "title": "Junior Suite - Lahore",
    "description": "Experience authentic Pakistani hospitality in our junior suite located in Lahore. Perfect for small families.",
    "location": "Lahore, Punjab",
    "capacity": 3,
    "pricePerNight": 33082,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"Smart TV\",\"Living Area\",\"Mini Bar\",\"Premium Coffee\",\"Work Station\",\"City View\"]",
    "size": "35-45 sqm",
    "bedType": "King Bed",
    "isAvailable": true,
    "featured": false
  },
  {
    "roomNumber": "LH-050",
    "type": "Executive Suite",
    "title": "Executive Suite - Lahore",
    "description": "Experience authentic Pakistani hospitality in our executive suite located in Lahore. Perfect for large families or groups.",
    "location": "Lahore, Punjab",
    "capacity": 6,
    "pricePerNight": 40116,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"55\\\" Smart TV\",\"Separate Living Room\",\"Mini Bar\",\"Premium Bedding\",\"Executive Lounge\",\"Butler Service\"]",
    "size": "50-65 sqm",
    "bedType": "King Bed + Sofa Bed",
    "isAvailable": true,
    "featured": true
  },
  {
    "roomNumber": "LH-051",
    "type": "Executive Suite",
    "title": "Executive Suite - Lahore",
    "description": "Experience authentic Pakistani hospitality in our executive suite located in Lahore. Perfect for large families or groups.",
    "location": "Lahore, Punjab",
    "capacity": 6,
    "pricePerNight": 36487,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"55\\\" Smart TV\",\"Separate Living Room\",\"Mini Bar\",\"Premium Bedding\",\"Executive Lounge\",\"Butler Service\"]",
    "size": "50-65 sqm",
    "bedType": "King Bed + Sofa Bed",
    "isAvailable": true,
    "featured": true
  },
  {
    "roomNumber": "LH-052",
    "type": "Executive Suite",
    "title": "Executive Suite - Lahore",
    "description": "Experience authentic Pakistani hospitality in our executive suite located in Lahore. Perfect for large families or groups.",
    "location": "Lahore, Punjab",
    "capacity": 6,
    "pricePerNight": 48689,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"55\\\" Smart TV\",\"Separate Living Room\",\"Mini Bar\",\"Premium Bedding\",\"Executive Lounge\",\"Butler Service\"]",
    "size": "50-65 sqm",
    "bedType": "King Bed + Sofa Bed",
    "isAvailable": true,
    "featured": true
  },
  {
    "roomNumber": "LH-053",
    "type": "Family Suite",
    "title": "Family Suite - Lahore",
    "description": "Experience authentic Pakistani hospitality in our family suite located in Lahore. Perfect for large families or groups.",
    "location": "Lahore, Punjab",
    "capacity": 6,
    "pricePerNight": 43168,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"Smart TV\",\"Kitchenette\",\"Separate Bedrooms\",\"Family Games\",\"Kids Welcome Pack\",\"Dining Area\"]",
    "size": "55-70 sqm",
    "bedType": "King + Twin Beds",
    "isAvailable": true,
    "featured": false
  },
  {
    "roomNumber": "LH-054",
    "type": "Family Suite",
    "title": "Family Suite - Lahore",
    "description": "Experience authentic Pakistani hospitality in our family suite located in Lahore. Perfect for large families or groups.",
    "location": "Lahore, Punjab",
    "capacity": 6,
    "pricePerNight": 41181,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"Smart TV\",\"Kitchenette\",\"Separate Bedrooms\",\"Family Games\",\"Kids Welcome Pack\",\"Dining Area\"]",
    "size": "55-70 sqm",
    "bedType": "King + Twin Beds",
    "isAvailable": true,
    "featured": false
  },
  {
    "roomNumber": "LH-055",
    "type": "Family Suite",
    "title": "Family Suite - Lahore",
    "description": "Experience authentic Pakistani hospitality in our family suite located in Lahore. Perfect for large families or groups.",
    "location": "Lahore, Punjab",
    "capacity": 6,
    "pricePerNight": 31785,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"Smart TV\",\"Kitchenette\",\"Separate Bedrooms\",\"Family Games\",\"Kids Welcome Pack\",\"Dining Area\"]",
    "size": "55-70 sqm",
    "bedType": "King + Twin Beds",
    "isAvailable": true,
    "featured": false
  },
  {
    "roomNumber": "LH-056",
    "type": "Presidential Suite",
    "title": "Presidential Suite - Lahore",
    "description": "Experience authentic Pakistani hospitality in our presidential suite located in Lahore. Perfect for large families or groups.",
    "location": "Lahore, Punjab",
    "capacity": 8,
    "pricePerNight": 67146,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"75\\\" Smart TV\",\"Full Kitchen\",\"Dining Area\",\"Premium Bedding\",\"Panoramic Views\",\"Concierge\",\"Butler Service\",\"Private Terrace\"]",
    "size": "80-120 sqm",
    "bedType": "King + Queen Beds",
    "isAvailable": true,
    "featured": true
  },
  {
    "roomNumber": "LH-057",
    "type": "Presidential Suite",
    "title": "Presidential Suite - Lahore",
    "description": "Experience authentic Pakistani hospitality in our presidential suite located in Lahore. Perfect for large families or groups.",
    "location": "Lahore, Punjab",
    "capacity": 8,
    "pricePerNight": 78173,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"75\\\" Smart TV\",\"Full Kitchen\",\"Dining Area\",\"Premium Bedding\",\"Panoramic Views\",\"Concierge\",\"Butler Service\",\"Private Terrace\"]",
    "size": "80-120 sqm",
    "bedType": "King + Queen Beds",
    "isAvailable": true,
    "featured": true
  },
  {
    "roomNumber": "LH-058",
    "type": "Royal Suite",
    "title": "Royal Suite - Lahore",
    "description": "Experience authentic Pakistani hospitality in our royal suite located in Lahore. Perfect for large families or groups.",
    "location": "Lahore, Punjab",
    "capacity": 10,
    "pricePerNight": 147228,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"85\\\" Smart TV\",\"Full Kitchen\",\"Multiple Bedrooms\",\"Dining Hall\",\"Premium Bedding\",\"Panoramic Views\",\"Personal Concierge\",\"24/7 Butler\",\"Private Terrace\",\"Jacuzzi\",\"Home Theater\"]",
    "size": "120-180 sqm",
    "bedType": "Multiple King Beds",
    "isAvailable": true,
    "featured": true
  },
  {
    "roomNumber": "SK-059",
    "type": "Budget Room",
    "title": "Budget Room - Sheikhupura",
    "description": "Experience authentic Pakistani hospitality in our budget room located in Sheikhupura. Perfect for solo travelers or couples.",
    "location": "Sheikhupura, Punjab",
    "capacity": 2,
    "pricePerNight": 4231,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"TV\",\"Attached Bathroom\",\"Room Service\"]",
    "size": "15-20 sqm",
    "bedType": "Double Bed",
    "isAvailable": true,
    "featured": false
  },
  {
    "roomNumber": "SK-060",
    "type": "Budget Room",
    "title": "Budget Room - Sheikhupura",
    "description": "Experience authentic Pakistani hospitality in our budget room located in Sheikhupura. Perfect for solo travelers or couples.",
    "location": "Sheikhupura, Punjab",
    "capacity": 2,
    "pricePerNight": 2870,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"TV\",\"Attached Bathroom\",\"Room Service\"]",
    "size": "15-20 sqm",
    "bedType": "Double Bed",
    "isAvailable": true,
    "featured": false
  },
  {
    "roomNumber": "SK-061",
    "type": "Budget Room",
    "title": "Budget Room - Sheikhupura",
    "description": "Experience authentic Pakistani hospitality in our budget room located in Sheikhupura. Perfect for solo travelers or couples.",
    "location": "Sheikhupura, Punjab",
    "capacity": 2,
    "pricePerNight": 3321,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"TV\",\"Attached Bathroom\",\"Room Service\"]",
    "size": "15-20 sqm",
    "bedType": "Double Bed",
    "isAvailable": true,
    "featured": false
  },
  {
    "roomNumber": "SK-062",
    "type": "Economy Room",
    "title": "Economy Room - Sheikhupura",
    "description": "Experience authentic Pakistani hospitality in our economy room located in Sheikhupura. Perfect for small families.",
    "location": "Sheikhupura, Punjab",
    "capacity": 3,
    "pricePerNight": 9446,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"LED TV\",\"Work Desk\",\"Mini Fridge\",\"Tea/Coffee Maker\"]",
    "size": "20-25 sqm",
    "bedType": "Queen Bed",
    "isAvailable": true,
    "featured": false
  },
  {
    "roomNumber": "SK-063",
    "type": "Economy Room",
    "title": "Economy Room - Sheikhupura",
    "description": "Experience authentic Pakistani hospitality in our economy room located in Sheikhupura. Perfect for small families.",
    "location": "Sheikhupura, Punjab",
    "capacity": 3,
    "pricePerNight": 7318,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"LED TV\",\"Work Desk\",\"Mini Fridge\",\"Tea/Coffee Maker\"]",
    "size": "20-25 sqm",
    "bedType": "Queen Bed",
    "isAvailable": true,
    "featured": false
  },
  {
    "roomNumber": "SK-064",
    "type": "Economy Room",
    "title": "Economy Room - Sheikhupura",
    "description": "Experience authentic Pakistani hospitality in our economy room located in Sheikhupura. Perfect for small families.",
    "location": "Sheikhupura, Punjab",
    "capacity": 3,
    "pricePerNight": 8425,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"LED TV\",\"Work Desk\",\"Mini Fridge\",\"Tea/Coffee Maker\"]",
    "size": "20-25 sqm",
    "bedType": "Queen Bed",
    "isAvailable": true,
    "featured": false
  },
  {
    "roomNumber": "SK-065",
    "type": "Standard Room",
    "title": "Standard Room - Sheikhupura",
    "description": "Experience authentic Pakistani hospitality in our standard room located in Sheikhupura. Perfect for solo travelers or couples.",
    "location": "Sheikhupura, Punjab",
    "capacity": 2,
    "pricePerNight": 10949,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"Smart TV\",\"Work Desk\",\"Mini Fridge\",\"Safe\",\"Premium Bedding\"]",
    "size": "25-30 sqm",
    "bedType": "King Bed",
    "isAvailable": true,
    "featured": false
  },
  {
    "roomNumber": "SK-066",
    "type": "Standard Room",
    "title": "Standard Room - Sheikhupura",
    "description": "Experience authentic Pakistani hospitality in our standard room located in Sheikhupura. Perfect for solo travelers or couples.",
    "location": "Sheikhupura, Punjab",
    "capacity": 2,
    "pricePerNight": 12279,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"Smart TV\",\"Work Desk\",\"Mini Fridge\",\"Safe\",\"Premium Bedding\"]",
    "size": "25-30 sqm",
    "bedType": "King Bed",
    "isAvailable": true,
    "featured": false
  },
  {
    "roomNumber": "SK-067",
    "type": "Standard Room",
    "title": "Standard Room - Sheikhupura",
    "description": "Experience authentic Pakistani hospitality in our standard room located in Sheikhupura. Perfect for solo travelers or couples.",
    "location": "Sheikhupura, Punjab",
    "capacity": 2,
    "pricePerNight": 13521,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"Smart TV\",\"Work Desk\",\"Mini Fridge\",\"Safe\",\"Premium Bedding\"]",
    "size": "25-30 sqm",
    "bedType": "King Bed",
    "isAvailable": true,
    "featured": false
  },
  {
    "roomNumber": "SK-068",
    "type": "Standard Room",
    "title": "Standard Room - Sheikhupura",
    "description": "Experience authentic Pakistani hospitality in our standard room located in Sheikhupura. Perfect for solo travelers or couples.",
    "location": "Sheikhupura, Punjab",
    "capacity": 2,
    "pricePerNight": 11991,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"Smart TV\",\"Work Desk\",\"Mini Fridge\",\"Safe\",\"Premium Bedding\"]",
    "size": "25-30 sqm",
    "bedType": "King Bed",
    "isAvailable": true,
    "featured": false
  },
  {
    "roomNumber": "SK-069",
    "type": "Deluxe Room",
    "title": "Deluxe Room - Sheikhupura",
    "description": "Experience authentic Pakistani hospitality in our deluxe room located in Sheikhupura. Perfect for small families.",
    "location": "Sheikhupura, Punjab",
    "capacity": 4,
    "pricePerNight": 15536,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"Smart TV\",\"Mini Bar\",\"Seating Area\",\"Premium Bedding\",\"Bathrobe\",\"City View\"]",
    "size": "30-40 sqm",
    "bedType": "King Bed + Sofa Bed",
    "isAvailable": true,
    "featured": false
  },
  {
    "roomNumber": "SK-070",
    "type": "Deluxe Room",
    "title": "Deluxe Room - Sheikhupura",
    "description": "Experience authentic Pakistani hospitality in our deluxe room located in Sheikhupura. Perfect for small families.",
    "location": "Sheikhupura, Punjab",
    "capacity": 4,
    "pricePerNight": 23856,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"Smart TV\",\"Mini Bar\",\"Seating Area\",\"Premium Bedding\",\"Bathrobe\",\"City View\"]",
    "size": "30-40 sqm",
    "bedType": "King Bed + Sofa Bed",
    "isAvailable": true,
    "featured": false
  },
  {
    "roomNumber": "SK-071",
    "type": "Deluxe Room",
    "title": "Deluxe Room - Sheikhupura",
    "description": "Experience authentic Pakistani hospitality in our deluxe room located in Sheikhupura. Perfect for small families.",
    "location": "Sheikhupura, Punjab",
    "capacity": 4,
    "pricePerNight": 22689,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"Smart TV\",\"Mini Bar\",\"Seating Area\",\"Premium Bedding\",\"Bathrobe\",\"City View\"]",
    "size": "30-40 sqm",
    "bedType": "King Bed + Sofa Bed",
    "isAvailable": true,
    "featured": false
  },
  {
    "roomNumber": "SK-072",
    "type": "Deluxe Room",
    "title": "Deluxe Room - Sheikhupura",
    "description": "Experience authentic Pakistani hospitality in our deluxe room located in Sheikhupura. Perfect for small families.",
    "location": "Sheikhupura, Punjab",
    "capacity": 4,
    "pricePerNight": 16310,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"Smart TV\",\"Mini Bar\",\"Seating Area\",\"Premium Bedding\",\"Bathrobe\",\"City View\"]",
    "size": "30-40 sqm",
    "bedType": "King Bed + Sofa Bed",
    "isAvailable": true,
    "featured": false
  },
  {
    "roomNumber": "SK-073",
    "type": "Business Room",
    "title": "Business Room - Sheikhupura",
    "description": "Experience authentic Pakistani hospitality in our business room located in Sheikhupura. Perfect for solo travelers or couples.",
    "location": "Sheikhupura, Punjab",
    "capacity": 2,
    "pricePerNight": 21398,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"Smart TV\",\"Executive Desk\",\"Printer Access\",\"Business Center\",\"Meeting Room Access\"]",
    "size": "28-35 sqm",
    "bedType": "King Bed",
    "isAvailable": true,
    "featured": false
  },
  {
    "roomNumber": "SK-074",
    "type": "Business Room",
    "title": "Business Room - Sheikhupura",
    "description": "Experience authentic Pakistani hospitality in our business room located in Sheikhupura. Perfect for solo travelers or couples.",
    "location": "Sheikhupura, Punjab",
    "capacity": 2,
    "pricePerNight": 29136,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"Smart TV\",\"Executive Desk\",\"Printer Access\",\"Business Center\",\"Meeting Room Access\"]",
    "size": "28-35 sqm",
    "bedType": "King Bed",
    "isAvailable": true,
    "featured": false
  },
  {
    "roomNumber": "SK-075",
    "type": "Business Room",
    "title": "Business Room - Sheikhupura",
    "description": "Experience authentic Pakistani hospitality in our business room located in Sheikhupura. Perfect for solo travelers or couples.",
    "location": "Sheikhupura, Punjab",
    "capacity": 2,
    "pricePerNight": 28127,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"Smart TV\",\"Executive Desk\",\"Printer Access\",\"Business Center\",\"Meeting Room Access\"]",
    "size": "28-35 sqm",
    "bedType": "King Bed",
    "isAvailable": true,
    "featured": false
  },
  {
    "roomNumber": "SK-076",
    "type": "Junior Suite",
    "title": "Junior Suite - Sheikhupura",
    "description": "Experience authentic Pakistani hospitality in our junior suite located in Sheikhupura. Perfect for small families.",
    "location": "Sheikhupura, Punjab",
    "capacity": 3,
    "pricePerNight": 30796,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"Smart TV\",\"Living Area\",\"Mini Bar\",\"Premium Coffee\",\"Work Station\",\"City View\"]",
    "size": "35-45 sqm",
    "bedType": "King Bed",
    "isAvailable": true,
    "featured": false
  },
  {
    "roomNumber": "SK-077",
    "type": "Junior Suite",
    "title": "Junior Suite - Sheikhupura",
    "description": "Experience authentic Pakistani hospitality in our junior suite located in Sheikhupura. Perfect for small families.",
    "location": "Sheikhupura, Punjab",
    "capacity": 3,
    "pricePerNight": 26496,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"Smart TV\",\"Living Area\",\"Mini Bar\",\"Premium Coffee\",\"Work Station\",\"City View\"]",
    "size": "35-45 sqm",
    "bedType": "King Bed",
    "isAvailable": true,
    "featured": false
  },
  {
    "roomNumber": "SK-078",
    "type": "Junior Suite",
    "title": "Junior Suite - Sheikhupura",
    "description": "Experience authentic Pakistani hospitality in our junior suite located in Sheikhupura. Perfect for small families.",
    "location": "Sheikhupura, Punjab",
    "capacity": 3,
    "pricePerNight": 34337,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"Smart TV\",\"Living Area\",\"Mini Bar\",\"Premium Coffee\",\"Work Station\",\"City View\"]",
    "size": "35-45 sqm",
    "bedType": "King Bed",
    "isAvailable": true,
    "featured": false
  },
  {
    "roomNumber": "SK-079",
    "type": "Executive Suite",
    "title": "Executive Suite - Sheikhupura",
    "description": "Experience authentic Pakistani hospitality in our executive suite located in Sheikhupura. Perfect for large families or groups.",
    "location": "Sheikhupura, Punjab",
    "capacity": 6,
    "pricePerNight": 40592,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"55\\\" Smart TV\",\"Separate Living Room\",\"Mini Bar\",\"Premium Bedding\",\"Executive Lounge\",\"Butler Service\"]",
    "size": "50-65 sqm",
    "bedType": "King Bed + Sofa Bed",
    "isAvailable": true,
    "featured": true
  },
  {
    "roomNumber": "SK-080",
    "type": "Executive Suite",
    "title": "Executive Suite - Sheikhupura",
    "description": "Experience authentic Pakistani hospitality in our executive suite located in Sheikhupura. Perfect for large families or groups.",
    "location": "Sheikhupura, Punjab",
    "capacity": 6,
    "pricePerNight": 42657,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"55\\\" Smart TV\",\"Separate Living Room\",\"Mini Bar\",\"Premium Bedding\",\"Executive Lounge\",\"Butler Service\"]",
    "size": "50-65 sqm",
    "bedType": "King Bed + Sofa Bed",
    "isAvailable": true,
    "featured": true
  },
  {
    "roomNumber": "SK-081",
    "type": "Executive Suite",
    "title": "Executive Suite - Sheikhupura",
    "description": "Experience authentic Pakistani hospitality in our executive suite located in Sheikhupura. Perfect for large families or groups.",
    "location": "Sheikhupura, Punjab",
    "capacity": 6,
    "pricePerNight": 46048,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"55\\\" Smart TV\",\"Separate Living Room\",\"Mini Bar\",\"Premium Bedding\",\"Executive Lounge\",\"Butler Service\"]",
    "size": "50-65 sqm",
    "bedType": "King Bed + Sofa Bed",
    "isAvailable": true,
    "featured": true
  },
  {
    "roomNumber": "SK-082",
    "type": "Family Suite",
    "title": "Family Suite - Sheikhupura",
    "description": "Experience authentic Pakistani hospitality in our family suite located in Sheikhupura. Perfect for large families or groups.",
    "location": "Sheikhupura, Punjab",
    "capacity": 6,
    "pricePerNight": 30679,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"Smart TV\",\"Kitchenette\",\"Separate Bedrooms\",\"Family Games\",\"Kids Welcome Pack\",\"Dining Area\"]",
    "size": "55-70 sqm",
    "bedType": "King + Twin Beds",
    "isAvailable": true,
    "featured": false
  },
  {
    "roomNumber": "SK-083",
    "type": "Family Suite",
    "title": "Family Suite - Sheikhupura",
    "description": "Experience authentic Pakistani hospitality in our family suite located in Sheikhupura. Perfect for large families or groups.",
    "location": "Sheikhupura, Punjab",
    "capacity": 6,
    "pricePerNight": 30928,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"Smart TV\",\"Kitchenette\",\"Separate Bedrooms\",\"Family Games\",\"Kids Welcome Pack\",\"Dining Area\"]",
    "size": "55-70 sqm",
    "bedType": "King + Twin Beds",
    "isAvailable": true,
    "featured": false
  },
  {
    "roomNumber": "SK-084",
    "type": "Family Suite",
    "title": "Family Suite - Sheikhupura",
    "description": "Experience authentic Pakistani hospitality in our family suite located in Sheikhupura. Perfect for large families or groups.",
    "location": "Sheikhupura, Punjab",
    "capacity": 6,
    "pricePerNight": 39988,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"Smart TV\",\"Kitchenette\",\"Separate Bedrooms\",\"Family Games\",\"Kids Welcome Pack\",\"Dining Area\"]",
    "size": "55-70 sqm",
    "bedType": "King + Twin Beds",
    "isAvailable": true,
    "featured": false
  },
  {
    "roomNumber": "SK-085",
    "type": "Presidential Suite",
    "title": "Presidential Suite - Sheikhupura",
    "description": "Experience authentic Pakistani hospitality in our presidential suite located in Sheikhupura. Perfect for large families or groups.",
    "location": "Sheikhupura, Punjab",
    "capacity": 8,
    "pricePerNight": 84082,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"75\\\" Smart TV\",\"Full Kitchen\",\"Dining Area\",\"Premium Bedding\",\"Panoramic Views\",\"Concierge\",\"Butler Service\",\"Private Terrace\"]",
    "size": "80-120 sqm",
    "bedType": "King + Queen Beds",
    "isAvailable": true,
    "featured": true
  },
  {
    "roomNumber": "SK-086",
    "type": "Presidential Suite",
    "title": "Presidential Suite - Sheikhupura",
    "description": "Experience authentic Pakistani hospitality in our presidential suite located in Sheikhupura. Perfect for large families or groups.",
    "location": "Sheikhupura, Punjab",
    "capacity": 8,
    "pricePerNight": 71250,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"75\\\" Smart TV\",\"Full Kitchen\",\"Dining Area\",\"Premium Bedding\",\"Panoramic Views\",\"Concierge\",\"Butler Service\",\"Private Terrace\"]",
    "size": "80-120 sqm",
    "bedType": "King + Queen Beds",
    "isAvailable": true,
    "featured": true
  },
  {
    "roomNumber": "SK-087",
    "type": "Royal Suite",
    "title": "Royal Suite - Sheikhupura",
    "description": "Experience authentic Pakistani hospitality in our royal suite located in Sheikhupura. Perfect for large families or groups.",
    "location": "Sheikhupura, Punjab",
    "capacity": 10,
    "pricePerNight": 101767,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"85\\\" Smart TV\",\"Full Kitchen\",\"Multiple Bedrooms\",\"Dining Hall\",\"Premium Bedding\",\"Panoramic Views\",\"Personal Concierge\",\"24/7 Butler\",\"Private Terrace\",\"Jacuzzi\",\"Home Theater\"]",
    "size": "120-180 sqm",
    "bedType": "Multiple King Beds",
    "isAvailable": true,
    "featured": true
  },
  {
    "roomNumber": "MT-088",
    "type": "Budget Room",
    "title": "Budget Room - Multan",
    "description": "Experience authentic Pakistani hospitality in our budget room located in Multan. Perfect for solo travelers or couples.",
    "location": "Multan, Punjab",
    "capacity": 2,
    "pricePerNight": 4134,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"TV\",\"Attached Bathroom\",\"Room Service\"]",
    "size": "15-20 sqm",
    "bedType": "Double Bed",
    "isAvailable": true,
    "featured": false
  },
  {
    "roomNumber": "MT-089",
    "type": "Budget Room",
    "title": "Budget Room - Multan",
    "description": "Experience authentic Pakistani hospitality in our budget room located in Multan. Perfect for solo travelers or couples.",
    "location": "Multan, Punjab",
    "capacity": 2,
    "pricePerNight": 4089,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"TV\",\"Attached Bathroom\",\"Room Service\"]",
    "size": "15-20 sqm",
    "bedType": "Double Bed",
    "isAvailable": true,
    "featured": false
  },
  {
    "roomNumber": "MT-090",
    "type": "Budget Room",
    "title": "Budget Room - Multan",
    "description": "Experience authentic Pakistani hospitality in our budget room located in Multan. Perfect for solo travelers or couples.",
    "location": "Multan, Punjab",
    "capacity": 2,
    "pricePerNight": 4604,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"TV\",\"Attached Bathroom\",\"Room Service\"]",
    "size": "15-20 sqm",
    "bedType": "Double Bed",
    "isAvailable": true,
    "featured": false
  },
  {
    "roomNumber": "MT-091",
    "type": "Economy Room",
    "title": "Economy Room - Multan",
    "description": "Experience authentic Pakistani hospitality in our economy room located in Multan. Perfect for small families.",
    "location": "Multan, Punjab",
    "capacity": 3,
    "pricePerNight": 9316,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"LED TV\",\"Work Desk\",\"Mini Fridge\",\"Tea/Coffee Maker\"]",
    "size": "20-25 sqm",
    "bedType": "Queen Bed",
    "isAvailable": true,
    "featured": false
  },
  {
    "roomNumber": "MT-092",
    "type": "Economy Room",
    "title": "Economy Room - Multan",
    "description": "Experience authentic Pakistani hospitality in our economy room located in Multan. Perfect for small families.",
    "location": "Multan, Punjab",
    "capacity": 3,
    "pricePerNight": 9485,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"LED TV\",\"Work Desk\",\"Mini Fridge\",\"Tea/Coffee Maker\"]",
    "size": "20-25 sqm",
    "bedType": "Queen Bed",
    "isAvailable": true,
    "featured": false
  },
  {
    "roomNumber": "MT-093",
    "type": "Economy Room",
    "title": "Economy Room - Multan",
    "description": "Experience authentic Pakistani hospitality in our economy room located in Multan. Perfect for small families.",
    "location": "Multan, Punjab",
    "capacity": 3,
    "pricePerNight": 5861,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"LED TV\",\"Work Desk\",\"Mini Fridge\",\"Tea/Coffee Maker\"]",
    "size": "20-25 sqm",
    "bedType": "Queen Bed",
    "isAvailable": true,
    "featured": false
  },
  {
    "roomNumber": "MT-094",
    "type": "Standard Room",
    "title": "Standard Room - Multan",
    "description": "Experience authentic Pakistani hospitality in our standard room located in Multan. Perfect for solo travelers or couples.",
    "location": "Multan, Punjab",
    "capacity": 2,
    "pricePerNight": 13117,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"Smart TV\",\"Work Desk\",\"Mini Fridge\",\"Safe\",\"Premium Bedding\"]",
    "size": "25-30 sqm",
    "bedType": "King Bed",
    "isAvailable": true,
    "featured": false
  },
  {
    "roomNumber": "MT-095",
    "type": "Standard Room",
    "title": "Standard Room - Multan",
    "description": "Experience authentic Pakistani hospitality in our standard room located in Multan. Perfect for solo travelers or couples.",
    "location": "Multan, Punjab",
    "capacity": 2,
    "pricePerNight": 11993,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"Smart TV\",\"Work Desk\",\"Mini Fridge\",\"Safe\",\"Premium Bedding\"]",
    "size": "25-30 sqm",
    "bedType": "King Bed",
    "isAvailable": true,
    "featured": false
  },
  {
    "roomNumber": "MT-096",
    "type": "Standard Room",
    "title": "Standard Room - Multan",
    "description": "Experience authentic Pakistani hospitality in our standard room located in Multan. Perfect for solo travelers or couples.",
    "location": "Multan, Punjab",
    "capacity": 2,
    "pricePerNight": 14887,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"Smart TV\",\"Work Desk\",\"Mini Fridge\",\"Safe\",\"Premium Bedding\"]",
    "size": "25-30 sqm",
    "bedType": "King Bed",
    "isAvailable": true,
    "featured": false
  },
  {
    "roomNumber": "MT-097",
    "type": "Standard Room",
    "title": "Standard Room - Multan",
    "description": "Experience authentic Pakistani hospitality in our standard room located in Multan. Perfect for solo travelers or couples.",
    "location": "Multan, Punjab",
    "capacity": 2,
    "pricePerNight": 14427,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"Smart TV\",\"Work Desk\",\"Mini Fridge\",\"Safe\",\"Premium Bedding\"]",
    "size": "25-30 sqm",
    "bedType": "King Bed",
    "isAvailable": true,
    "featured": false
  },
  {
    "roomNumber": "MT-098",
    "type": "Deluxe Room",
    "title": "Deluxe Room - Multan",
    "description": "Experience authentic Pakistani hospitality in our deluxe room located in Multan. Perfect for small families.",
    "location": "Multan, Punjab",
    "capacity": 4,
    "pricePerNight": 16506,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"Smart TV\",\"Mini Bar\",\"Seating Area\",\"Premium Bedding\",\"Bathrobe\",\"City View\"]",
    "size": "30-40 sqm",
    "bedType": "King Bed + Sofa Bed",
    "isAvailable": true,
    "featured": false
  },
  {
    "roomNumber": "MT-099",
    "type": "Deluxe Room",
    "title": "Deluxe Room - Multan",
    "description": "Experience authentic Pakistani hospitality in our deluxe room located in Multan. Perfect for small families.",
    "location": "Multan, Punjab",
    "capacity": 4,
    "pricePerNight": 22476,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"Smart TV\",\"Mini Bar\",\"Seating Area\",\"Premium Bedding\",\"Bathrobe\",\"City View\"]",
    "size": "30-40 sqm",
    "bedType": "King Bed + Sofa Bed",
    "isAvailable": true,
    "featured": false
  },
  {
    "roomNumber": "MT-100",
    "type": "Deluxe Room",
    "title": "Deluxe Room - Multan",
    "description": "Experience authentic Pakistani hospitality in our deluxe room located in Multan. Perfect for small families.",
    "location": "Multan, Punjab",
    "capacity": 4,
    "pricePerNight": 19900,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"Smart TV\",\"Mini Bar\",\"Seating Area\",\"Premium Bedding\",\"Bathrobe\",\"City View\"]",
    "size": "30-40 sqm",
    "bedType": "King Bed + Sofa Bed",
    "isAvailable": true,
    "featured": false
  },
  {
    "roomNumber": "MT-101",
    "type": "Deluxe Room",
    "title": "Deluxe Room - Multan",
    "description": "Experience authentic Pakistani hospitality in our deluxe room located in Multan. Perfect for small families.",
    "location": "Multan, Punjab",
    "capacity": 4,
    "pricePerNight": 24517,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"Smart TV\",\"Mini Bar\",\"Seating Area\",\"Premium Bedding\",\"Bathrobe\",\"City View\"]",
    "size": "30-40 sqm",
    "bedType": "King Bed + Sofa Bed",
    "isAvailable": true,
    "featured": false
  },
  {
    "roomNumber": "MT-102",
    "type": "Business Room",
    "title": "Business Room - Multan",
    "description": "Experience authentic Pakistani hospitality in our business room located in Multan. Perfect for solo travelers or couples.",
    "location": "Multan, Punjab",
    "capacity": 2,
    "pricePerNight": 21931,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"Smart TV\",\"Executive Desk\",\"Printer Access\",\"Business Center\",\"Meeting Room Access\"]",
    "size": "28-35 sqm",
    "bedType": "King Bed",
    "isAvailable": true,
    "featured": false
  },
  {
    "roomNumber": "MT-103",
    "type": "Business Room",
    "title": "Business Room - Multan",
    "description": "Experience authentic Pakistani hospitality in our business room located in Multan. Perfect for solo travelers or couples.",
    "location": "Multan, Punjab",
    "capacity": 2,
    "pricePerNight": 20008,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"Smart TV\",\"Executive Desk\",\"Printer Access\",\"Business Center\",\"Meeting Room Access\"]",
    "size": "28-35 sqm",
    "bedType": "King Bed",
    "isAvailable": true,
    "featured": false
  },
  {
    "roomNumber": "MT-104",
    "type": "Business Room",
    "title": "Business Room - Multan",
    "description": "Experience authentic Pakistani hospitality in our business room located in Multan. Perfect for solo travelers or couples.",
    "location": "Multan, Punjab",
    "capacity": 2,
    "pricePerNight": 27375,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"Smart TV\",\"Executive Desk\",\"Printer Access\",\"Business Center\",\"Meeting Room Access\"]",
    "size": "28-35 sqm",
    "bedType": "King Bed",
    "isAvailable": true,
    "featured": false
  },
  {
    "roomNumber": "MT-105",
    "type": "Junior Suite",
    "title": "Junior Suite - Multan",
    "description": "Experience authentic Pakistani hospitality in our junior suite located in Multan. Perfect for small families.",
    "location": "Multan, Punjab",
    "capacity": 3,
    "pricePerNight": 32078,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"Smart TV\",\"Living Area\",\"Mini Bar\",\"Premium Coffee\",\"Work Station\",\"City View\"]",
    "size": "35-45 sqm",
    "bedType": "King Bed",
    "isAvailable": true,
    "featured": false
  },
  {
    "roomNumber": "MT-106",
    "type": "Junior Suite",
    "title": "Junior Suite - Multan",
    "description": "Experience authentic Pakistani hospitality in our junior suite located in Multan. Perfect for small families.",
    "location": "Multan, Punjab",
    "capacity": 3,
    "pricePerNight": 33448,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"Smart TV\",\"Living Area\",\"Mini Bar\",\"Premium Coffee\",\"Work Station\",\"City View\"]",
    "size": "35-45 sqm",
    "bedType": "King Bed",
    "isAvailable": true,
    "featured": false
  },
  {
    "roomNumber": "MT-107",
    "type": "Junior Suite",
    "title": "Junior Suite - Multan",
    "description": "Experience authentic Pakistani hospitality in our junior suite located in Multan. Perfect for small families.",
    "location": "Multan, Punjab",
    "capacity": 3,
    "pricePerNight": 28132,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"Smart TV\",\"Living Area\",\"Mini Bar\",\"Premium Coffee\",\"Work Station\",\"City View\"]",
    "size": "35-45 sqm",
    "bedType": "King Bed",
    "isAvailable": true,
    "featured": false
  },
  {
    "roomNumber": "MT-108",
    "type": "Executive Suite",
    "title": "Executive Suite - Multan",
    "description": "Experience authentic Pakistani hospitality in our executive suite located in Multan. Perfect for large families or groups.",
    "location": "Multan, Punjab",
    "capacity": 6,
    "pricePerNight": 44030,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"55\\\" Smart TV\",\"Separate Living Room\",\"Mini Bar\",\"Premium Bedding\",\"Executive Lounge\",\"Butler Service\"]",
    "size": "50-65 sqm",
    "bedType": "King Bed + Sofa Bed",
    "isAvailable": true,
    "featured": true
  },
  {
    "roomNumber": "MT-109",
    "type": "Executive Suite",
    "title": "Executive Suite - Multan",
    "description": "Experience authentic Pakistani hospitality in our executive suite located in Multan. Perfect for large families or groups.",
    "location": "Multan, Punjab",
    "capacity": 6,
    "pricePerNight": 43016,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"55\\\" Smart TV\",\"Separate Living Room\",\"Mini Bar\",\"Premium Bedding\",\"Executive Lounge\",\"Butler Service\"]",
    "size": "50-65 sqm",
    "bedType": "King Bed + Sofa Bed",
    "isAvailable": true,
    "featured": true
  },
  {
    "roomNumber": "MT-110",
    "type": "Executive Suite",
    "title": "Executive Suite - Multan",
    "description": "Experience authentic Pakistani hospitality in our executive suite located in Multan. Perfect for large families or groups.",
    "location": "Multan, Punjab",
    "capacity": 6,
    "pricePerNight": 37044,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"55\\\" Smart TV\",\"Separate Living Room\",\"Mini Bar\",\"Premium Bedding\",\"Executive Lounge\",\"Butler Service\"]",
    "size": "50-65 sqm",
    "bedType": "King Bed + Sofa Bed",
    "isAvailable": true,
    "featured": true
  },
  {
    "roomNumber": "MT-111",
    "type": "Family Suite",
    "title": "Family Suite - Multan",
    "description": "Experience authentic Pakistani hospitality in our family suite located in Multan. Perfect for large families or groups.",
    "location": "Multan, Punjab",
    "capacity": 6,
    "pricePerNight": 31798,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"Smart TV\",\"Kitchenette\",\"Separate Bedrooms\",\"Family Games\",\"Kids Welcome Pack\",\"Dining Area\"]",
    "size": "55-70 sqm",
    "bedType": "King + Twin Beds",
    "isAvailable": true,
    "featured": false
  },
  {
    "roomNumber": "MT-112",
    "type": "Family Suite",
    "title": "Family Suite - Multan",
    "description": "Experience authentic Pakistani hospitality in our family suite located in Multan. Perfect for large families or groups.",
    "location": "Multan, Punjab",
    "capacity": 6,
    "pricePerNight": 37427,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"Smart TV\",\"Kitchenette\",\"Separate Bedrooms\",\"Family Games\",\"Kids Welcome Pack\",\"Dining Area\"]",
    "size": "55-70 sqm",
    "bedType": "King + Twin Beds",
    "isAvailable": true,
    "featured": false
  },
  {
    "roomNumber": "MT-113",
    "type": "Family Suite",
    "title": "Family Suite - Multan",
    "description": "Experience authentic Pakistani hospitality in our family suite located in Multan. Perfect for large families or groups.",
    "location": "Multan, Punjab",
    "capacity": 6,
    "pricePerNight": 41543,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"Smart TV\",\"Kitchenette\",\"Separate Bedrooms\",\"Family Games\",\"Kids Welcome Pack\",\"Dining Area\"]",
    "size": "55-70 sqm",
    "bedType": "King + Twin Beds",
    "isAvailable": true,
    "featured": false
  },
  {
    "roomNumber": "MT-114",
    "type": "Presidential Suite",
    "title": "Presidential Suite - Multan",
    "description": "Experience authentic Pakistani hospitality in our presidential suite located in Multan. Perfect for large families or groups.",
    "location": "Multan, Punjab",
    "capacity": 8,
    "pricePerNight": 59597,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"75\\\" Smart TV\",\"Full Kitchen\",\"Dining Area\",\"Premium Bedding\",\"Panoramic Views\",\"Concierge\",\"Butler Service\",\"Private Terrace\"]",
    "size": "80-120 sqm",
    "bedType": "King + Queen Beds",
    "isAvailable": true,
    "featured": true
  },
  {
    "roomNumber": "MT-115",
    "type": "Presidential Suite",
    "title": "Presidential Suite - Multan",
    "description": "Experience authentic Pakistani hospitality in our presidential suite located in Multan. Perfect for large families or groups.",
    "location": "Multan, Punjab",
    "capacity": 8,
    "pricePerNight": 79938,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"75\\\" Smart TV\",\"Full Kitchen\",\"Dining Area\",\"Premium Bedding\",\"Panoramic Views\",\"Concierge\",\"Butler Service\",\"Private Terrace\"]",
    "size": "80-120 sqm",
    "bedType": "King + Queen Beds",
    "isAvailable": true,
    "featured": true
  },
  {
    "roomNumber": "MT-116",
    "type": "Royal Suite",
    "title": "Royal Suite - Multan",
    "description": "Experience authentic Pakistani hospitality in our royal suite located in Multan. Perfect for large families or groups.",
    "location": "Multan, Punjab",
    "capacity": 10,
    "pricePerNight": 119438,
    "images": "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\"]",
    "amenities": "[\"Free WiFi\",\"Air Conditioning\",\"85\\\" Smart TV\",\"Full Kitchen\",\"Multiple Bedrooms\",\"Dining Hall\",\"Premium Bedding\",\"Panoramic Views\",\"Personal Concierge\",\"24/7 Butler\",\"Private Terrace\",\"Jacuzzi\",\"Home Theater\"]",
    "size": "120-180 sqm",
    "bedType": "Multiple King Beds",
    "isAvailable": true,
    "featured": true
  }
];

  // Create rooms
  const createdRooms = [];
  for (const roomData of rooms) {
    const room = await prisma.room.create({ data: roomData });
    createdRooms.push(room);
  }

  // Create Pakistani attractions
  await prisma.attraction.createMany({
    data: [
      {
        title: 'Badshahi Mosque',
        subtitle: 'Historic Mughal Architecture',
        description: 'One of the largest mosques in the world, built in 1671 by Mughal Emperor Aurangzeb. A masterpiece of Mughal architecture.',
        image: 'https://via.placeholder.com/400x250/4A90E6/FFFFFF?text=Badshahi+Mosque',
        location: 'Lahore, Punjab',
      },
      {
        title: 'Lahore Fort (Shahi Qila)',
        subtitle: 'UNESCO World Heritage Site',
        description: 'A magnificent fort complex with stunning palaces, gardens, and museums showcasing centuries of history.',
        image: 'https://via.placeholder.com/400x250/FF8C00/FFFFFF?text=Lahore+Fort',
        location: 'Lahore, Punjab',
      },
      {
        title: 'Shalimar Gardens',
        subtitle: 'Mughal Gardens',
        description: 'Beautiful Mughal gardens built in 1641, featuring terraced levels, fountains, and lush greenery.',
        image: 'https://via.placeholder.com/400x250/008000/FFFFFF?text=Shalimar+Gardens',
        location: 'Lahore, Punjab',
      },
      {
        title: 'Tomb of Shah Rukn-e-Alam',
        subtitle: 'Sufi Shrine',
        description: 'A magnificent mausoleum and one of the most impressive Sufi shrines in Pakistan, built in 1320-1324.',
        image: 'https://via.placeholder.com/400x250/8B0000/FFFFFF?text=Shah+Rukn+Alam',
        location: 'Multan, Punjab',
      },
      {
        title: 'Hiran Minar',
        subtitle: 'Mughal Monument',
        description: 'A unique Mughal-era monument built by Emperor Jahangir, featuring a water tank and beautiful architecture.',
        image: 'https://via.placeholder.com/400x250/4B0082/FFFFFF?text=Hiran+Minar',
        location: 'Sheikhupura, Punjab',
      },
      {
        title: 'Okara Garrison',
        subtitle: 'Military Heritage',
        description: 'Historic military cantonment area with colonial-era architecture and military museums.',
        image: 'https://via.placeholder.com/400x250/2F4F4F/FFFFFF?text=Okara+Garrison',
        location: 'Okara, Punjab',
      },
    ],
  });

  // Hash passwords
  const adminPassword = await bcrypt.hash('admin123', 10);
  const userPassword = await bcrypt.hash('user123', 10);

  // Create admin user
  const adminUser = await prisma.user.create({
    data: {
      name: 'Admin User',
      email: 'admin@hotelogix.com',
      password: adminPassword,
      phone: '+92-300-1234567',
      role: 'admin',
    },
  });

  // Create sample user
  const sampleUser = await prisma.user.create({
    data: {
      name: 'Ahmed Khan',
      email: 'ahmed@example.com',
      password: userPassword,
      phone: '+92-321-9876543',
      role: 'user',
    },
  });

  // Create sample bookings
  await prisma.booking.createMany({
    data: [
      {
        userId: sampleUser.id,
        roomId: createdRooms[10].id,
        checkIn: new Date('2025-12-15'),
        checkOut: new Date('2025-12-18'),
        totalPrice: createdRooms[10].pricePerNight * 3,
        status: 'confirmed',
      },
      {
        userId: sampleUser.id,
        roomId: createdRooms[25].id,
        checkIn: new Date('2025-12-20'),
        checkOut: new Date('2025-12-23'),
        totalPrice: createdRooms[25].pricePerNight * 3,
        status: 'pending',
      },
    ],
  });

  console.log('✅ Pakistan Hotels database seeded successfully!');
  console.log('📊 Created:');
  console.log(`  - ${rooms.length} Rooms across 4 cities`);
  console.log('  - 6 Pakistani Attractions');
  console.log('  - 1 Admin User (admin@hotelogix.com)');
  console.log('  - 1 Sample User (ahmed@example.com)');
  console.log('  - 2 Sample Bookings');
  console.log('\n📍 Cities: Okara, Lahore, Sheikhupura, Multan');
  console.log('💰 Price Range: PKR 2,000 - PKR 150,000');
}

main()
  .catch((e) => {
    console.error('❌ Error seeding database:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
